import { MASTER_AGENT_PROMPT } from './mcp-catalog'

export interface PromptItem {
  category: string
  prompt: string
}

export { MASTER_AGENT_PROMPT }

export const PROMPT_CATEGORIES = [
  'General',
  'Compliance',
  'Yield',
  'Staking',
  'Vault',
  'Payments',
  'Audit',
  'Transfer',
  'Portfolio',
  'Developer',
  'Planner',
  'Judge Demo',
] as const

export type PromptCategory = (typeof PROMPT_CATEGORIES)[number]

export const PROMPT_LIBRARY: PromptItem[] = [
  { category: 'General', prompt: 'What is MERIDIAN and how do I use it as an AI agent?' },
  { category: 'General', prompt: 'List every MCP tool and categorize read vs write.' },
  { category: 'General', prompt: 'What can I do without connecting a wallet?' },
  { category: 'General', prompt: 'Explain the full agent flow from objective to blockchain.' },
  { category: 'General', prompt: 'What network is MERIDIAN deployed on?' },
  { category: 'General', prompt: 'Show me all deployed contract addresses.' },
  { category: 'General', prompt: 'What is the difference between read and write MCP tools?' },
  { category: 'General', prompt: 'Give me a 60-second overview for a hackathon judge.' },
  { category: 'General', prompt: 'What happens after I sign a transaction?' },
  { category: 'General', prompt: 'How does the dashboard relate to MCP?' },
  {
    category: 'Compliance',
    prompt:
      'Check compliance status for account-hash-267bc977600c9512c0ce5e96af4d0057d514998cc752e28b8f5e91b654a72c27',
  },
  { category: 'Compliance', prompt: 'Is this holder registered and sanctions-cleared?' },
  { category: 'Compliance', prompt: 'Prepare register_holder for a new compliant holder.' },
  { category: 'Compliance', prompt: 'What role is required to revoke a holder?' },
  { category: 'Compliance', prompt: 'Explain ERC-3643 style compliance in MERIDIAN.' },
  { category: 'Compliance', prompt: 'Screen a holder before MRWA transfer.' },
  {
    category: 'Compliance',
    prompt: 'Build revoke_holder for a sanctioned account (compliance officer only).',
  },
  { category: 'Compliance', prompt: 'List compliance-related MCP tools only.' },
  { category: 'Compliance', prompt: 'What attestation bytes are needed for register_holder?' },
  { category: 'Compliance', prompt: 'Compare holder status before and after registration.' },
  { category: 'Yield', prompt: 'What is the current MRWA yield APY?' },
  { category: 'Yield', prompt: 'Show yield distribution history.' },
  { category: 'Yield', prompt: 'Why is APY zero right now?' },
  { category: 'Yield', prompt: 'When was the last yield distribution?' },
  { category: 'Yield', prompt: 'How is estimatedApyBps calculated?' },
  { category: 'Yield', prompt: 'Explain total staked vs total supply.' },
  { category: 'Yield', prompt: 'What triggers yield distribution on-chain?' },
  { category: 'Yield', prompt: 'Read yield metrics without wallet.' },
  { category: 'Yield', prompt: 'Summarize yield agent decisions from backend.' },
  { category: 'Yield', prompt: 'What era IDs appear in yield history?' },
  { category: 'Staking', prompt: 'List top Casper validators for delegation.' },
  {
    category: 'Staking',
    prompt: 'Delegate 500 CSPR to the first validator. My public key is 01...',
  },
  { category: 'Staking', prompt: 'What is the minimum delegation amount on Casper?' },
  { category: 'Staking', prompt: 'Explain native delegate_stake vs vault deposit.' },
  {
    category: 'Staking',
    prompt: 'Build delegate_stake for validator 01... with 500000000000 motes.',
  },
  { category: 'Staking', prompt: 'Why did my stake fail with DelegationAmountTooSmall?' },
  { category: 'Staking', prompt: 'Show validator stake weights from list_validators.' },
  { category: 'Staking', prompt: 'How much gas does delegation require?' },
  { category: 'Staking', prompt: 'After I sign delegation, what explorer URL should I use?' },
  {
    category: 'Staking',
    prompt: 'Confirm my delegation amount meets 500 CSPR minimum before wallet.',
  },
  { category: 'Vault', prompt: 'Explain MERIDIAN StakingVault vs native delegation.' },
  { category: 'Vault', prompt: 'Build deposit_to_vault for 10 CSPR.' },
  { category: 'Vault', prompt: 'What is attachedValueMotes on vault deposit?' },
  { category: 'Vault', prompt: 'Who can call restake on the vault?' },
  { category: 'Vault', prompt: 'Build restake between two validators (curator only).' },
  { category: 'Vault', prompt: 'Build distribute_rewards for era 0.' },
  { category: 'Vault', prompt: 'What on-chain role does restake require?' },
  { category: 'Vault', prompt: 'Compare vault deposit to native delegate_stake.' },
  { category: 'Payments', prompt: 'Explain x402 machine commerce in MERIDIAN.' },
  { category: 'Payments', prompt: 'How do I pay for premium audit data?' },
  { category: 'Payments', prompt: 'What does subscribe_audit return without payment?' },
  { category: 'Payments', prompt: 'Walk me through HTTP 402 to unlocked resource.' },
  { category: 'Payments', prompt: 'What facilitator URL does MERIDIAN use?' },
  { category: 'Payments', prompt: 'Pay for yield-rate premium resource via x402.' },
  { category: 'Payments', prompt: 'Explain verify and settle for CSPR micropayments.' },
  { category: 'Payments', prompt: 'How can an agent pay autonomously with x402?' },
  { category: 'Audit', prompt: 'Subscribe to audit summaries with x402 payment.' },
  { category: 'Audit', prompt: 'What events appear in the audit trail?' },
  { category: 'Audit', prompt: 'Explain AuditAgent adversarial review.' },
  { category: 'Audit', prompt: 'Show recent audit summaries from backend.' },
  { category: 'Audit', prompt: 'How does MeridianAudit contract relate to MCP?' },
  { category: 'Audit', prompt: 'Generate hourly audit summary workflow.' },
  { category: 'Audit', prompt: 'What is CEP-88 in MERIDIAN context?' },
  { category: 'Audit', prompt: 'Compare free events vs premium subscribe_audit.' },
  { category: 'Transfer', prompt: 'Transfer 1000 MRWA to account-hash-... My public key is 01...' },
  { category: 'Transfer', prompt: 'Build unsigned transfer_token transaction.' },
  { category: 'Transfer', prompt: 'Check recipient compliance before transfer.' },
  { category: 'Transfer', prompt: 'Explain MRWA fixed supply — no minting.' },
  { category: 'Transfer', prompt: 'What is the gas payment on transfer_token?' },
  { category: 'Transfer', prompt: 'Verify token package hash before transfer.' },
  { category: 'Transfer', prompt: 'Summarize transfer after wallet signature.' },
  { category: 'Transfer', prompt: 'Can I transfer without compliance registration?' },
  { category: 'Portfolio', prompt: 'Give me a portfolio snapshot: token info, yield, validators.' },
  { category: 'Portfolio', prompt: 'Summarize my MRWA exposure and staking options.' },
  { category: 'Portfolio', prompt: 'What read tools form a good pre-flight checklist?' },
  { category: 'Portfolio', prompt: 'Combine get_token_info and get_yield_rate in one answer.' },
  { category: 'Portfolio', prompt: 'What on-chain activity exists for MRWA today?' },
  { category: 'Portfolio', prompt: 'Explain total supply and staking ratio.' },
  { category: 'Portfolio', prompt: 'List all protocol KPIs from MCP read tools.' },
  { category: 'Portfolio', prompt: 'What would a compliance officer monitor daily?' },
  { category: 'Developer', prompt: 'Show MCP health endpoint response.' },
  { category: 'Developer', prompt: 'How do I run MERIDIAN MCP locally with stdio?' },
  { category: 'Developer', prompt: 'What env vars does the MCP server need?' },
  { category: 'Developer', prompt: 'Explain Streamable HTTP transport for MCP.' },
  { category: 'Developer', prompt: 'How does frontend /api/mcp proxy work?' },
  { category: 'Developer', prompt: 'Run planner execute API with objective query.' },
  { category: 'Developer', prompt: 'How do agent traces stream over SSE?' },
  { category: 'Developer', prompt: 'What migration creates meridian_agent_traces?' },
  { category: 'Developer', prompt: 'Debug MCP tool validation errors.' },
  { category: 'Developer', prompt: 'Compare local tx builder vs remote MCP for writes.' },
  { category: 'Planner', prompt: 'Planner: What is the current MRWA yield APY?' },
  { category: 'Planner', prompt: 'Planner: Register a new compliant holder.' },
  { category: 'Planner', prompt: 'Planner: Delegate 500 CSPR to best validator.' },
  { category: 'Planner', prompt: 'Planner: Check compliance then transfer MRWA.' },
  { category: 'Planner', prompt: 'Planner: Full judge demo in 5 steps.' },
  { category: 'Planner', prompt: 'Show planner reasoning trace for my objective.' },
  { category: 'Planner', prompt: 'Planner: Read-first then write workflow.' },
  { category: 'Planner', prompt: 'Execute planner with my connected wallet public key.' },
  { category: 'Planner', prompt: 'Explain planner tool discovery step.' },
  { category: 'Planner', prompt: 'What traces appear in Agent Activity Center?' },
  { category: 'Judge Demo', prompt: 'Judge demo step 1: read APY without wallet.' },
  { category: 'Judge Demo', prompt: 'Judge demo step 2: list validators.' },
  { category: 'Judge Demo', prompt: 'Judge demo step 3: build 500 CSPR delegation.' },
  { category: 'Judge Demo', prompt: 'Judge demo step 4: x402 premium audit.' },
  { category: 'Judge Demo', prompt: 'Judge demo step 5: watch Agent Activity Center.' },
  { category: 'Judge Demo', prompt: 'Complete 60-second MERIDIAN demo script.' },
  { category: 'Judge Demo', prompt: 'Prove MCP is the product, dashboard is visualizer.' },
  { category: 'Judge Demo', prompt: 'Show finalized transaction on testnet.cspr.live.' },
  { category: 'Judge Demo', prompt: 'Demonstrate read-before-write agent discipline.' },
  { category: 'Judge Demo', prompt: 'End-to-end: Claude → MCP → Wallet → Chain → Timeline.' },
]

export const PROMPT_COUNT = PROMPT_LIBRARY.length
